# Generated by Django 2.1.4 on 2020-08-04 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('time_to_be_sent', models.TimeField(blank=True, null=True)),
                ('message_type', models.CharField(max_length=255)),
                ('message_sent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('time_sent', models.TimeField(blank=True, null=True)),
                ('message_type', models.CharField(max_length=255)),
                ('message_opened', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Walkathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('starting_time', models.TimeField()),
                ('starting_day', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Walker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walker_number', models.CharField(default=0, max_length=255)),
                ('distance_to_walk', models.CharField(default=8, max_length=255, null=True)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('total_walked_distance', models.IntegerField(default=0, null=True)),
                ('walk_method', models.CharField(default='Route', max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('pace', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=20, null=True)),
                ('new_notification', models.BooleanField(blank=True, default=False)),
                ('steps_walked', models.CharField(default=0, max_length=255, null=True)),
                ('time_started', models.TimeField(blank=True, null=True)),
                ('time_ended', models.TimeField(blank=True, null=True)),
                ('total_received_notifications', models.IntegerField(default=0, null=True)),
                ('total_opened_notifications', models.IntegerField(default=0, null=True)),
                ('milestones', models.TextField(default=[], null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
