# Generated by Django 2.1.4 on 2020-09-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='messages_received',
            field=models.TextField(default=[], null=True),
        ),
    ]
