# Generated by Django 2.1.4 on 2020-08-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walker',
            name='time_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='walker',
            name='time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
