# Generated by Django 2.1.4 on 2020-08-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0002_auto_20200804_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walker',
            name='time_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
