# Generated by Django 2.1.4 on 2020-09-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0002_walker_messages_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
