# Generated by Django 2.1.4 on 2020-07-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0003_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.TextField(default='10km'),
        ),
    ]
