# Generated by Django 2.1.4 on 2020-09-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0003_walker_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='walker_leader',
            field=models.BooleanField(default=False),
        ),
    ]
