# Generated by Django 2.1.4 on 2020-08-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0004_streaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='stream_id',
            field=models.CharField(default='HAF4Qtgury01lFYRYSMuj02AW4X2BNIDOiVbAwhgfy9kE', max_length=500),
        ),
    ]
