# Generated by Django 2.1.4 on 2020-09-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0004_walker_walker_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='generated_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='walker',
            name='generated_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
