# Generated by Django 2.1.4 on 2020-07-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0004_auto_20200723_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race', to='walkathon.Runner'),
        ),
    ]
