# Generated by Django 2.1.4 on 2020-08-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0005_streaming_stream_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='stream_started',
            field=models.BooleanField(default=False),
        ),
    ]
