# Generated by Django 2.1.4 on 2020-07-31 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walkathon', '0005_auto_20200723_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('time_to_be_sent', models.TimeField(null=True)),
                ('message_type', models.CharField(max_length=255)),
                ('message_sent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('time_sent', models.TimeField(null=True)),
                ('message_type', models.CharField(max_length=255)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Walkathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('starting_time', models.TimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Walker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walker_number', models.CharField(max_length=255, null=True)),
                ('distance_to_walk', models.CharField(max_length=255, null=True)),
                ('fcm_token', models.TextField()),
                ('total_walked_distance', models.CharField(max_length=255, null=True)),
                ('walk_method', models.CharField(max_length=255, null=True)),
                ('team', models.CharField(max_length=255, null=True)),
                ('pace', models.CharField(max_length=255, null=True)),
                ('device_type', models.CharField(max_length=20, null=True)),
                ('new_notification', models.BooleanField(default=False)),
                ('time_started', models.TimeField(null=True)),
                ('time_ended', models.TimeField(null=True)),
                ('total_received_notifications', models.IntegerField(default=0)),
                ('total_opened_notifications', models.IntegerField(default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='race',
            name='runner',
        ),
        migrations.RemoveField(
            model_name='race',
            name='runner_profile',
        ),
        migrations.RemoveField(
            model_name='runner',
            name='runner_profile',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='Runner',
        ),
    ]
