# Generated by Django 2.1.4 on 2020-09-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0005_auto_20200912_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('security_tips', models.TextField()),
                ('frequently_asked_questions', models.TextField()),
                ('terms_and_conditions', models.TextField()),
            ],
        ),
    ]
