# Generated by Django 2.1.4 on 2020-09-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0006_informationscreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='route_coordinates',
            field=models.TextField(default=[]),
        ),
    ]
