# Generated by Django 2.1.4 on 2020-08-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0006_streaming_stream_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessages',
            name='time_sent',
        ),
        migrations.AddField(
            model_name='systemmessages',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='systemmessages',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemmessages',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='usermessages',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usermessages',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermessages',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='walkathon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='walkathon',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='walker',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='walker',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='streaming',
            name='stream_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
