# Generated by Django 2.1.4 on 2020-08-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0006_auto_20200731_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='message_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walker',
            name='steps_walked',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
