# Generated by Django 2.1.4 on 2020-09-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0007_walker_route_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walker',
            name='total_walked_distance',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
    ]
