# Generated by Django 2.1.4 on 2020-08-02 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0007_auto_20200802_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkathon',
            name='starting_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='walkathon',
            name='starting_time',
            field=models.DateTimeField(),
        ),
    ]
