# Generated by Django 2.1.4 on 2020-09-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0008_auto_20200913_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkathon',
            name='banners',
            field=models.TextField(default=[]),
        ),
    ]
