# Generated by Django 2.1.4 on 2020-08-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0008_auto_20200814_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walker',
            name='new_notification',
        ),
        migrations.RemoveField(
            model_name='walker',
            name='pace',
        ),
        migrations.RemoveField(
            model_name='walker',
            name='total_opened_notifications',
        ),
        migrations.RemoveField(
            model_name='walker',
            name='total_received_notifications',
        ),
        migrations.AddField(
            model_name='systemmessages',
            name='send_condition',
            field=models.CharField(choices=[('4km1', '4 km 1st Milestone'), ('4km2', '4 km 2nd Milestone')], default=('4km1', '4 km 1st Milestone'), max_length=255),
        ),
        migrations.AlterField(
            model_name='systemmessages',
            name='message_type',
            field=models.CharField(choices=[('Individual', 'System Generated and Walker Activity Related'), ('Blast', 'Marketing Team')], default=('Blast', 'Marketing Team'), max_length=255),
        ),
    ]
