# Generated by Django 2.1.4 on 2020-08-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0008_auto_20200802_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkathon',
            name='starting_time',
            field=models.TimeField(),
        ),
    ]
