# Generated by Django 2.1.4 on 2020-08-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0009_auto_20200802_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkathon',
            name='year',
            field=models.IntegerField(),
        ),
    ]
