# Generated by Django 2.1.4 on 2020-10-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0009_walkathon_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walker',
            name='uid',
            field=models.BigIntegerField(default=0),
        ),
    ]
