# Generated by Django 2.1.4 on 2020-08-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0010_auto_20200802_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walker',
            name='fcm_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='walker',
            name='total_opened_notifications',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='walker',
            name='total_received_notifications',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='walker',
            name='total_walked_distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='walker',
            name='walker_number',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
