# Generated by Django 2.1.4 on 2020-08-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0011_auto_20200815_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='blast_messages_read',
            field=models.TextField(default=[], null=True),
        ),
    ]
