# Generated by Django 2.1.4 on 2020-08-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0011_auto_20200803_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='milestones',
            field=models.TextField(default=[], null=True),
        ),
    ]
