# Generated by Django 2.1.4 on 2020-08-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0012_walker_blast_messages_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessages',
            name='user_profile',
        ),
        migrations.RenameField(
            model_name='walker',
            old_name='blast_messages_read',
            new_name='messages_read',
        ),
        migrations.DeleteModel(
            name='UserMessages',
        ),
    ]
