# Generated by Django 2.1.4 on 2020-08-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0013_auto_20200816_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='messages_received',
            field=models.TextField(default=[], null=True),
        ),
    ]
