# Generated by Django 2.1.4 on 2020-08-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0015_remove_walker_messages_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='messages_received',
            field=models.TextField(default=[], null=True),
        ),
    ]
