# Generated by Django 2.1.4 on 2020-08-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0016_walker_messages_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walker',
            name='messages_received',
        ),
    ]
