# Generated by Django 2.1.4 on 2020-08-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0017_remove_walker_messages_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessages',
            name='message_opened',
            field=models.BooleanField(default=False),
        ),
    ]
