# Generated by Django 2.1.4 on 2020-08-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0018_systemmessages_message_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='stream_ended',
            field=models.BooleanField(default=False),
        ),
    ]
