# Generated by Django 2.1.4 on 2020-08-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0019_streaming_stream_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='stream_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='systemmessages',
            name='send_condition',
            field=models.CharField(choices=[('4km1', '4 km 1st Milestone'), ('4km2', '4 km 2nd Milestone'), ('4km3', '4 km 3rd Milestone'), ('4km4', '4 km 4th Milestone'), ('8km1', '8 km 1st Milestone'), ('8km2', '8 km 2nd Milestone'), ('8km3', '8 km 3rd Milestone'), ('8km4', '8 km 4th Milestone'), ('NOW', 'SEND NOW - WARNING will send immediately after you press save'), ('SCHEDULED', 'Scheduled - Date and Time need to be specified'), ('NEW_STREAM_STARTED', 'Stream started')], default=('4km1', '4 km 1st Milestone'), max_length=255),
        ),
    ]
